export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA';
export const SET_GLOBAL_DATA = 'SET_GLOBAL_DATA';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const GET_PERSON_LIST_DATA = 'GET_PERSON_LIST_DATA';
export const SET_PERSON_LIST_DATA = 'SET_PERSON_LIST_DATA';
export const GET_PERSON_DATA = 'GET_PERSON_DATA';
export const SET_PERSON_DATA = 'SET_PERSON_DATA';
